### ISSUE TITLE
Abstract over WebError

### ISSUE THREAD

**Issue by gabro** [buildo/nozzle#19]
## requirements

The WebError family is rather arbitrary.
We should allow defining custom errors.

**Comment by calippo** [comment]
I'm currently experiencing this very issue.

Does `WebError` really needs to be defined as `sealed`?
Each web service handle errors in its own way, I don't think it makes sense to force a predefined structure. 
Ok... we're losing control on `MatchError`, but this lack of flexibility is really frustrating.

Another solution would be to create a "free text error", but I don't think it's safer than a run-time `MatchError`.

**Comment by calippo** [comment]
Closed in https://github.com/buildo/nozzle/pull/24
